name: release
on:
  push:
    branches:
      - main
    paths:
      - VERSION.txt

  workflow_run:
    workflows: ["build"]
    types: [completed]

env:
  PROJECT_NAME: imgui_glfw_vulkan_template

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: salsify/action-detect-and-tag-new-version@v2
        with:
          version-command: |
            cat VERSION.txt
